feat: error on unknown option

diff --git a/with_dockerfile b/with_dockerfile
--- a/with_dockerfile
+++ b/with_dockerfile
@@ -45,6 +45,7 @@ while true; do
     --artifact             ) artifacts=("${artifacts[@]}" "$2"); shift 2 ;;
     --artifacts-save-path  ) artifacts_save_path=$2; shift 2 ;;
     --remove-image-on-exit ) remove_image_on_exit="yes"; shift ;;
+    --*                    ) echo "error: unknown option $1"; exit 1 ;;
     * ) break ;;
   esac
 done
diff --git a/with_gitlab_mr_comment b/with_gitlab_mr_comment
--- a/with_gitlab_mr_comment
+++ b/with_gitlab_mr_comment
@@ -25,6 +25,7 @@ while test "$#" -gt 0; do
     --comment-on-cancel  ) comment_on_cancel=$2; shift 2 ;;
     --comment-on-success ) comment_on_success=$2; shift 2 ;;
     --comment-on-fail    ) comment_on_fail=$2; shift 2 ;;
+    --*                  ) echo "error: unknown option $1"; exit 1 ;;
     *                    ) break ;;
   esac
 done
diff --git a/with_gitlab_pipeline b/with_gitlab_pipeline
--- a/with_gitlab_pipeline
+++ b/with_gitlab_pipeline
@@ -22,6 +22,7 @@ while test "$#" -gt 0; do
     --commit-sha        ) commit_sha=$2; shift 2 ;;
     --build-system-name ) build_system_name=$2; shift 2 ;;
     --build-url         ) build_url=$2; shift 2 ;;
+    --*                 ) echo "error: unknown option $1"; exit 1 ;;
     *                   ) break ;;
   esac
 done
diff --git a/with_slack_message b/with_slack_message
--- a/with_slack_message
+++ b/with_slack_message
@@ -36,6 +36,7 @@ while test "$#" -gt 0; do
     --message-on-fail    ) message_on_fail=$2; shift 2 ;;
     --user-name          ) user_name=$2; shift 2 ;;
     --user-icon          ) user_icon=$2; shift 2 ;;
+    --*                  ) echo "error: unknown option $1"; exit 1 ;;
     *                    ) break ;;
   esac
 done
